# -*- coding: utf-8 -*-
"""klasifikasi gojek nlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z1QDXh9E847soz3cEDL9xtJV8GgNAKtb
"""

# 1. Import library
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# 2. Upload file CSV
from google.colab import files
uploaded = files.upload()

# 3. Load dataset
df = pd.read_csv("gojek.csv")
df.head()

# Cek informasi kolom
df.info()

# Cek nilai null
print(df.isnull().sum())

# Menghapus baris yang mengandung nilai kosong
df = df.dropna()

# Encoding semua kolom kategori
label_encoders = {}
for column in df.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column])
    label_encoders[column] = le

# Split data untuk training dan testing
X = df.drop('score', axis=1)
y = df['score']

# Split 80% training dan 20% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Melatih Naive Bayes model
model = GaussianNB()
model.fit(X_train, y_train)

# Prediksi
y_pred = model.predict(X_test)

# Evaluasi
print("Akurasi:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Visualisasi
import matplotlib.pyplot as plt
import seaborn as sns

# Calculate accuracy
acc = accuracy_score(y_test, y_pred)  # Calculate accuracy and assign to 'acc'

# Calculate confusion matrix
cm = confusion_matrix(y_test, y_pred) # Calculate confusion matrix and assign to 'cm'


## a. Akurasi Bar Chart
plt.figure(figsize=(4,4))
plt.bar(['Akurasi'], [acc], color='skyblue')
plt.ylim(0,1)
plt.title("Akurasi Model")
plt.ylabel("Nilai Akurasi")
plt.text(0, acc + 0.02, f"{acc:.2f}", ha='center', fontsize=12)
plt.show()

## b. Confusion Matrix Heatmap
plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix")
plt.xlabel("Prediksi")
plt.ylabel("Aktual")
plt.show()

## c. Classification Report Heatmap
report_dict = classification_report(y_test, y_pred, output_dict=True)
df_report = pd.DataFrame(report_dict).transpose()
df_visual = df_report.iloc[:-3, :][['precision', 'recall', 'f1-score']]

plt.figure(figsize=(8,4))
sns.heatmap(df_visual, annot=True, cmap='YlGnBu', fmt='.2f')
plt.title("Classification Report (Precision, Recall, F1-score)")
plt.show()